### ISSUE TITLE
Just some suggestions for Documentation improvements

### ISSUE THREAD

**Issue by kuttnerdd** [drlogout/iredmail-cli#10]
just some small suggestions to strenghten the meanings:

## Text Improvement

![image](https://user-images.githubusercontent.com/32716729/42909904-e30f4130-8ae5-11e8-8dca-78a13ded5f05.png)
All emails sent to **adress** post@example.com and hello@example.com will be delivered to the same **mailbox** info@example.com.

---
## Text Improvement
![image](https://user-images.githubusercontent.com/32716729/42909919-eb7e67e2-8ae5-11e8-8ac5-3c50dc51ab68.png)
Instead of „Multiple destination addresses are possible.“ I would stick to the example formulation from above e.g.:
All emails sent to the **mailbox** info@example.com will be delivered to **address** tech@company.com and support@example.net too.

---
## Funtionality proposal
![image](https://user-images.githubusercontent.com/32716729/42909925-f1b4bb02-8ae5-11e8-90d3-398c68f14ec7.png)
Display in list form possible for all mailboxes like `$ iredmail-cli forwarding list`?
sth like `$ iredmail-cli keep-copy list` useful? not sure if needed in real life, but from disk-space optimization view maybe interesting and relevant

**Comment by drlogout** [comment]
Thanks for the suggestions. I updated the Readme.

You can run `iredmail-cli forwarding list` and there you can see which forwarding will keep a copy in the mailbox (in the KEEP COPY IN MAILBOX column).
